name: Build, Analyze, and Scan

on:
  push:
    branches:
      - main

jobs:
  build-analyze-scan:
    name: Build, Analyze, and Scan
    runs-on: self-hosted

    env:
      DOCKER_CLI_ACI: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build and analyze with SonarQube
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-host: ${{ secrets.SONAR_HOST_URL }}

      - name: npm install dependencies
        run: npm install

      - name: Trivy File Scan
        run: trivy fs . > trivyfs.txt

      - name: Docker Build and Push
        run: |
          docker build -t bharathcv/tic-tac-toe .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push bharathcv/tic-tac-toe
